### ISSUE TITLE
Checklist: Migrate campaign metadata from Ashes & remove campaign run IDs.

### ISSUE THREAD

**Issue by chloealee** [DoSomething/infrastructure#61]
### Overview
In order to retire Ashes, we need to move legacy campaigns to the Rogue database. [This document](https://docs.google.com/document/d/1_B1499L9xhJQfaYDa2-Sjsuj3IRtLKb_1qYLvNAXsbI/edit#) has more information about what data will be migrated to Rogue and how we will deprecate runs. Below is a checklist of the order of operations for the migration to successfully run.

### Order of Operations
First, we need to **create the new Campaign IDs table** in Rogue (based on old IDs/Run IDs):

- [x] Team Bleed to merge [PR](https://github.com/DoSomething/rogue/pull/783) to migrate all legacy campaigns from Ashes to Rogue.
- [x] Morgan to complete taking the Campaigns table from Rogue and piping it into Quasar 
- [x] Team Bleed to run/test migration script to get all legacy campaigns into Rogue on QA.
- [x] ALL TEAMS: Check that data looks good & everything still works as expected on QA! 
- [x] Run migration script to get all legacy campaigns into Rogue on production. 
- [x] ALL TEAMS: Check that data looks good & everything still [works as expected](https://docs.google.com/spreadsheets/d/1Y3j9mQ2b4hOlyl6xPBd-iUT5CY7rklMmKpGlgkSVKbE/edit#gid=1646989618) on production!

Once we have that table, we'll **update signups & posts from old runs to their new canonical IDs**:
- [x] **Team Bleed** to write script to update all signup and post `campaign_id`s in Rogue's `signups` and `posts` table according to new data in `campaigns` table.
- [x] Remove logic from Rogue which queries on `campaign_run_id` on QA! (DoSomething/rogue#788)
- [x] ~Deploy the Rogue fix for `campaign_run_id` and new signups to production. (DoSomething/rogue#788)~ Whoops, [never mind](https://github.com/DoSomething/rogue/pull/795)!
- [x] Update Rogue Admin [to read campaign data from the above table](https://github.com/DoSomething/rogue/pull/794), so we don't get errors when trying to query Ashes for these new consolidated campaign IDs. This has been tested by @DFurnes and @katiecrane on QA (pre-script) and all looks well!
- [x] **Team Bleed** to run the script to update signups/post's `campaign_id` on QA.
- [x] **Team Storm** will the update signup/post campaign IDs on Quasar QA [based on these SQL queries](https://www.pivotaltracker.com/n/projects/2076969/stories/162313317).
- [x] **Team Bleed:** Check that data looks good & everything still [works as expected](https://docs.google.com/spreadsheets/d/1Y3j9mQ2b4hOlyl6xPBd-iUT5CY7rklMmKpGlgkSVKbE/edit#gid=1646989618) on QA.
- [x] **Team Storm:** Check that data looks good & everything still [works as expected](https://docs.google.com/spreadsheets/d/1Y3j9mQ2b4hOlyl6xPBd-iUT5CY7rklMmKpGlgkSVKbE/edit#gid=1646989618) on Quasar QA.
- [x] **Team Storm:** Check that data looks good & everything still [works as expected](https://docs.google.com/spreadsheets/d/1Y3j9mQ2b4hOlyl6xPBd-iUT5CY7rklMmKpGlgkSVKbE/edit#gid=1646989618) on Looker QA.
- [x] **Team Bleed** to run the script to update signups/post's `campaign_id` on production.
- [x] **Team O'Doyle** to deploy DoSomething/gambit-conversations#456 which updates to filter by `campaign_id` when checking posts/signups (was [previously only filtering by `campaign_run_id`](https://dosomething.slack.com/archives/C0YGXUE01/p1544202493049900)).
- [x] **Team Bleed** to update Rogue to ignore `campaign_run_id` values when querying, creating, and updating signups or posts (by deploying DoSomething/rogue#798 to production).
- [x] **Team Storm** will the update signup/post campaign IDs on Quasar Production [based on these SQL queries](https://www.pivotaltracker.com/n/projects/2076969/stories/162313317).
- [x] **Team Bleed:** Check that data looks good & everything still [works as expected](https://docs.google.com/spreadsheets/d/1Y3j9mQ2b4hOlyl6xPBd-iUT5CY7rklMmKpGlgkSVKbE/edit#gid=1646989618) on production.
- [x] **Team Storm:** Check that data looks good & everything still [works as expected](https://docs.google.com/spreadsheets/d/1Y3j9mQ2b4hOlyl6xPBd-iUT5CY7rklMmKpGlgkSVKbE/edit#gid=1646989618) on Quasar production.
- [x] **Team Storm:** Check that data looks good & everything still [works as expected](https://docs.google.com/spreadsheets/d/1Y3j9mQ2b4hOlyl6xPBd-iUT5CY7rklMmKpGlgkSVKbE/edit#gid=1646989618) on Looker production.
- [x] **ALL TEAMS:** Check that data looks good & everything still [works as expected](https://docs.google.com/spreadsheets/d/1Y3j9mQ2b4hOlyl6xPBd-iUT5CY7rklMmKpGlgkSVKbE/edit#gid=1646989618) on production!

Once this script has run, **we can update front-ends to exclude Run IDs** anytime:
- [x] Phoenix will stop sending `campaign_run_id` on the next production deploy.
- [x] Gambit to exclude `campaign_run_id` from all Rogue requests (alter signups filtering by `campaign_id` instead of `campaign_run_id` when checking for `signup.why_participated`)

Other things to think about in 2019:
- [ ] Galleries previously showed all runs for a multi-run campaign, now they'll just show the "latest" campaign. We may need to rethink for pre-seeding campaigns

**Comment by DFurnes** [comment]
We [finished this up today](https://dosomething.slack.com/archives/C782XBKDM/p1544201612056200) and everything is looking good!
